#!/usr/bin/env python3
# -*- coding: utf-8 -*-
protocol = {
    'LOTUS': 'crawling.files.lotus.lotuscrawler.LotusOne',
    'EWS': 'crawling.files.ewscrawler.MultiEWS',
    'FTP': 'crawling.files.ftpcrawler.FTPOne',
    'HDFS': 'crawling.files.hdfscrawler.HDFSOne',
    'IMAP': 'crawling.files.imapcrawler.MultiIMAP',
    'NFS': 'crawling.files.nfscrawler.NFSOne',
    'OSS': 'crawling.files.osscrawler.factory',
    'POP3': 'crawling.files.pop3crawler.MultiPOP3',
    'SFTP': 'crawling.files.sftpcrawler.SFTPOne',
    'SHAREPOINT': 'crawling.files.sharepointcrawler.SharePointOne',
    'AWS': 'crawling.files.osscrawler.AWSCloudOne',
    'SMB': 'crawling.files.smbcrawler.SMBOne',
    'WEBDAV': 'crawling.files.webdavcrawler.WebDavOne',
    'NUT': 'crawling.files.webdavcrawler.NutCloud',
    'HBASEREST': 'crawling.database.hbaserestcrawler.HBaseRest',
    'REDIS': 'crawling.database.rediscrawler.RedisOne',
    'MONGO': 'crawling.database.mongocrawler.MongoOne',
    'DBProxy': 'crawling.database.dbproxy.dbpcrawler.DBProxy',
    'GRIDFS': 'crawling.files.gridfscrawler.GRIDFS',
    'IGUO': 'crawling.files.iguocrawler.Iguo',
    'UDS': 'crawling.files.uds.udscrawler.UDS',
    'EYOU': 'crawling.files.eyoucrawler.EYou',
    'UDSREST': 'crawling.files.udsrestcrawler.UDSREST',
    'WEBURL': 'crawling.files.multiwebcrawler.WebURL',
    'COREMAIL': 'crawling.files.coremailcrawler.CoreMailOne',
    'WKDOC': 'crawling.files.wpscrawler.WKDOC',
    'AISHU': 'crawling.files.aishucrawler.AiShu',
    'SEEYON': 'crawling.files.seeyoncrawler.SeeyonClient'
}

iterator = {
    'LOTUS': 'crawling.files.lotus.lotuscrawler.LotusIterator',
    'EWS': 'crawling.files.ewscrawler.MultiEWSIterator',
    'FTP': 'crawling.files.ftpcrawler.FTPIterator',
    'HDFS': 'crawling.files.hdfscrawler.HDFSIterator',
    'HTTPGET': 'crawling.files.httpcrawler.HttpGetIterator',
    'IMAP': 'crawling.files.imapcrawler.MultiIMAPIterator',
    'NFS': 'crawling.files.nfscrawler.NFSIterator',
    'OSS': 'crawling.files.osscrawler.OSSIterator',
    'POP3': 'crawling.files.pop3crawler.MultiPOP3Iterator',
    'SFTP': 'crawling.files.sftpcrawler.SFTPIterator',
    'SHAREPOINT': 'crawling.files.sharepointcrawler.SharePointIterator',
    'AWS': 'crawling.files.osscrawler.OSSIterator',
    'SMB': 'crawling.files.smbcrawler.SMBIterator',
    'WEBDAV': 'crawling.files.webdavcrawler.WebDavIterator',
    'NUT': 'crawling.files.webdavcrawler.NutIterator',
    'HBASEREST': 'crawling.database.hbaserestcrawler.HBaseIterator',
    'REDIS': 'crawling.database.rediscrawler.RedisIterator',
    'MONGO': 'crawling.database.mongocrawler.MongoIterator',
    'DBProxy': 'crawling.database.dbproxy.dbpcrawler.DBProxyIterator',
    'DBProxyAppend': 'crawling.database.dbproxy.dbpcrawler.DBProxyAppendIterator',
    'SHANXIOA': 'crawling.files.oa.ShanxiOAIterator',
    'GRIDFS': 'crawling.files.gridfscrawler.GRIDFSIterator',
    'IGUO': 'crawling.files.iguocrawler.IguoIterator',
    'UDS': 'crawling.files.uds.udscrawler.UDSIterator',
    'EYOU': 'crawling.files.eyoucrawler.EYouIterator',
    'UDSREST': 'crawling.files.udsrestcrawler.UDSRESTIterator',
    'WEBURL': 'crawling.files.multiwebcrawler.WebURLIterator',
    'COREMAIL': 'crawling.files.coremailcrawler.CoreMailIterator',
    'WKDOC': 'crawling.files.wpscrawler.WKDOCIterator',
    'AISHU': 'crawling.files.aishucrawler.AiShuIterator',
    'SEEYON': 'crawling.files.seeyoncrawler.SeeyonIterator'
}
